import type { User } from '@supabase/supabase-js';

/** Trigger yaratgan zaxira: user_ + UUID (tiressiz 32 ta hex) */
const AUTO_PROFILE_USERNAME = /^user_[0-9a-f]{32}$/i;

export function isAutoGeneratedProfileUsername(username: string): boolean {
  return AUTO_PROFILE_USERNAME.test(username.trim());
}

function firstNonEmptyMetaString(
  user: User | null,
  keys: readonly string[],
): string | null {
  if (!user?.user_metadata) return null;
  const m = user.user_metadata as Record<string, unknown>;
  for (const k of keys) {
    const v = m[k];
    if (typeof v === 'string' && v.trim()) return v.trim();
  }
  return null;
}

/**
 * Dashboard / profil sarlavhasi: ro‘yxatdan o‘tishdagi nom yoki email, avtomatik user_... emas.
 */
export function getProfileDisplayName(
  profile: { username: string },
  user: User | null,
): string {
  const raw = profile.username?.trim() ?? '';
  if (raw && !isAutoGeneratedProfileUsername(raw)) {
    return raw;
  }

  const fromMeta = firstNonEmptyMetaString(user, [
    'full_name',
    'name',
    'display_name',
    'preferred_username',
    'username',
  ] as const);
  if (fromMeta && !isAutoGeneratedProfileUsername(fromMeta)) {
    return fromMeta;
  }

  const email = user?.email?.trim();
  if (email) {
    const local = email.split('@')[0]?.trim();
    if (local) return local;
  }

  return 'Sarguzashtchi';
}
