import { useState, useEffect } from 'react';
import { useAuth } from '@/contexts/AuthContext';
import { useProfile } from '@/hooks/useProfile';
import AVATARS, { getAvatarEmoji } from '@/lib/avatars';
import { getProfileDisplayName, isAutoGeneratedProfileUsername } from '@/lib/displayName';
import { useNavigate, Navigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { ArrowLeft } from 'lucide-react';
import { toast } from 'sonner';
import HeartCountdownHint from '@/components/HeartCountdownHint';
import { Input } from '@/components/ui/input';

const MAX_NAME_LEN = 40;

const ProfilePage = () => {
  const { user } = useAuth();
  const { profile, updateProfile } = useProfile();
  const navigate = useNavigate();
  const [selectedAvatar, setSelectedAvatar] = useState(1);
  const [nameDraft, setNameDraft] = useState('');

  useEffect(() => {
    if (!profile) return;
    setSelectedAvatar(profile.avatar_id ?? 1);
    const u = profile.username?.trim() ?? '';
    setNameDraft(isAutoGeneratedProfileUsername(u) ? '' : u);
  }, [profile]);

  if (!user) return <Navigate to="/auth" replace />;
  if (!profile) return null;

  const storedName =
    profile.username?.trim() && !isAutoGeneratedProfileUsername(profile.username.trim())
      ? profile.username.trim()
      : '';
  const nameChanged = nameDraft.trim() !== storedName;
  const canSaveName =
    nameChanged && nameDraft.trim().length >= 2 && nameDraft.trim().length <= MAX_NAME_LEN;

  const handleSaveAvatar = async () => {
    try {
      await updateProfile.mutateAsync({ avatar_id: selectedAvatar });
      toast.success('Avatar yangilandi! 🎉');
    } catch {
      toast.error('Avatarni yangilab bo‘lmadi');
    }
  };

  const handleSaveName = async () => {
    const next = nameDraft.trim();
    if (next.length < 2) {
      toast.error('Ism kamida 2 ta belgidan iborat bo‘lsin.');
      return;
    }
    if (next.length > MAX_NAME_LEN) {
      toast.error(`Ism ${MAX_NAME_LEN} belgidan oshmasligi kerak.`);
      return;
    }
    try {
      await updateProfile.mutateAsync({ username: next });
      toast.success('Ismingiz saqlandi');
    } catch (e: unknown) {
      const err = e as { code?: string; message?: string };
      const msg = String(err?.message ?? '');
      if (err?.code === '23505' || msg.includes('duplicate') || msg.includes('unique')) {
        toast.error('Bu ism band, boshqasini kiriting.');
      } else {
        toast.error('Ismni saqlab bo‘lmadi. Qayta urinib ko‘ring.');
      }
    }
  };

  return (
    <div className="min-h-screen bg-background">
      <header className="sticky top-0 z-10 bg-card/80 backdrop-blur-lg border-b border-border">
        <div className="container mx-auto flex items-center gap-4 px-4 py-3">
          <button onClick={() => { navigate('/dashboard'); }} className="rounded-xl p-2 hover:bg-muted transition-colors active:scale-95">
            <ArrowLeft className="h-5 w-5" />
          </button>
          <h1 className="text-xl font-extrabold text-foreground">👤 Mening profilim</h1>
        </div>
      </header>

      <main className="container mx-auto px-4 py-8 max-w-lg">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
        >
          <div className="text-center mb-8">
            <motion.div
              className="text-8xl mb-3 inline-block"
              animate={{ y: [0, -6, 0] }}
              transition={{ duration: 3, repeat: Infinity, ease: 'easeInOut' }}
            >
              {getAvatarEmoji(selectedAvatar)}
            </motion.div>
            <h2 className="text-2xl font-black text-foreground">
              {getProfileDisplayName(profile, user)}
            </h2>
            <p className="text-muted-foreground font-semibold">
              {profile.level}-daraja · {profile.xp.toLocaleString()} tajriba balli
            </p>
          </div>

          <div className="rounded-2xl bg-card p-6 shadow-md mb-6">
            <h3 className="font-extrabold text-foreground mb-2">Ismingiz</h3>
            <p className="text-xs text-muted-foreground mb-3">
              Boshqa sahifalarda shu nom ko‘rinadi (kamida 2 ta belgi).
            </p>
            <div className="flex flex-col gap-3 sm:flex-row sm:items-center">
              <Input
                value={nameDraft}
                onChange={e => { setNameDraft(e.target.value); }}
                placeholder="Masalan: Ali yoki Malika"
                maxLength={MAX_NAME_LEN}
                className="rounded-xl border-border bg-background font-semibold"
                autoComplete="nickname"
              />
              {canSaveName && (
                <motion.button
                  initial={{ opacity: 0, y: 6 }}
                  animate={{ opacity: 1, y: 0 }}
                  type="button"
                  disabled={updateProfile.isPending}
                  onClick={() => { void handleSaveName(); }}
                  className="shrink-0 rounded-xl bg-primary px-4 py-2.5 font-bold text-primary-foreground shadow-md disabled:opacity-60"
                >
                  {updateProfile.isPending ? 'Saqlanmoqda…' : 'Saqlash'}
                </motion.button>
              )}
            </div>
          </div>

          <div className="rounded-2xl bg-card p-6 shadow-md mb-6">
            <h3 className="font-extrabold text-foreground mb-4">Avatarni tanlang</h3>
            <div className="grid grid-cols-4 gap-3">
              {AVATARS.map(avatar => (
                <motion.button
                  key={avatar.id}
                  whileTap={{ scale: 0.9 }}
                  type="button"
                  onClick={() => { setSelectedAvatar(avatar.id); }}
                  className={`flex h-16 w-16 items-center justify-center rounded-2xl text-3xl transition-all ${
                    selectedAvatar === avatar.id
                      ? 'bg-primary/10 border-2 border-primary shadow-md'
                      : 'bg-muted border-2 border-transparent hover:border-border'
                  }`}
                >
                  {avatar.emoji}
                </motion.button>
              ))}
            </div>
            {selectedAvatar !== profile.avatar_id && (
              <motion.button
                initial={{ opacity: 0, y: 8 }}
                animate={{ opacity: 1, y: 0 }}
                type="button"
                onClick={() => { void handleSaveAvatar(); }}
                disabled={updateProfile.isPending}
                className="mt-4 w-full rounded-xl bg-primary py-3 font-bold text-primary-foreground shadow-lg shadow-primary/25 transition-all active:scale-[0.97] disabled:opacity-60"
              >
                Avatarni saqlash ✨
              </motion.button>
            )}
          </div>

          <div className="rounded-2xl bg-card p-6 shadow-md">
            <h3 className="font-extrabold text-foreground mb-4">Statistika</h3>
            <div className="space-y-3">
              <div className="flex items-center justify-between">
                <span className="text-muted-foreground font-semibold">🔥 Ketma-ketlik</span>
                <span className="font-bold text-foreground">{profile.streak_days} kun</span>
              </div>
              <div className="flex items-center justify-between gap-2">
                <span className="text-muted-foreground font-semibold">❤️ Yurakchalar</span>
                <div className="flex flex-col items-end gap-0.5 text-right">
                  <span className="font-bold text-foreground">{profile.hearts}/5</span>
                  <HeartCountdownHint
                    hearts={profile.hearts}
                    heartsLastRegen={profile.hearts_last_regen}
                    className="text-[11px] text-muted-foreground"
                  />
                </div>
              </div>
              <div className="flex items-center justify-between">
                <span className="text-muted-foreground font-semibold">⭐ Jami tajriba balli</span>
                <span className="font-bold text-foreground">{profile.xp.toLocaleString()}</span>
              </div>
              <div className="flex items-center justify-between">
                <span className="text-muted-foreground font-semibold">🎯 Daraja</span>
                <span className="font-bold text-foreground">{profile.level}</span>
              </div>
            </div>
          </div>
        </motion.div>
      </main>
    </div>
  );
};

export default ProfilePage;
